# Embed a file as a C byte array header.
# usage: cmake -DINPUT=<file> -DOUTPUT=<header> -DNAME=<symbol> -P embed.cmake

file(READ "${INPUT}" hex HEX)
string(LENGTH "${hex}" hex_len)
math(EXPR n_bytes "${hex_len} / 2")

# 0xNN, per byte, a line break every 32 bytes
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){32})" "\\1\n" bytes "${bytes}")

file(WRITE "${OUTPUT}.tmp"
"// Generated by tools/server/dashboard/embed.cmake from ${NAME} - do not edit.\n"
"#pragma once\n"
"#include <cstddef>\n"
"static const unsigned char ${NAME}[] = {\n${bytes}\n};\n"
"static const size_t ${NAME}_len = ${n_bytes};\n")

# only touch the header when the contents change, to avoid needless rebuilds
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${OUTPUT}.tmp" "${OUTPUT}")
file(REMOVE "${OUTPUT}.tmp")
